### ISSUE TITLE
Exceptions while server is running

### ISSUE THREAD

**Issue by aleighco** [casperge/RealisticSeasons-issues#187]
paper 1.19.3

[07:00:43 WARN]: [RealisticSeasons] Task #120 for RealisticSeasons v10.2.2 generated an exception
java.lang.NullPointerException: Cannot invoke "me.casperge.realisticseasons.data.chunksaver.ChunkDataHandler.logChunk(me.casperge.realisticseasons.season.SeasonChunk)" because the return value of "me.casperge.realisticseasons.RealisticSeasons.getAsyncChunkHandler()" is null
        at me.casperge.realisticseasons.runnables.WinterBlockTicker.run(WinterBlockTicker.java:200) ~[RealisticSeasons-10.2.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-373]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-373]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by casperge** [comment]
Working on a fix this weekend

**Comment by aleighco** [comment]
Fantastic! This is one of our favorite plugins.

**Comment by aleighco** [comment]
Maybe/probably? related we are seeing the temperature calculations not taking effect, like if it is cold (it's winter now on our sever), if you stand close to a campfire it is not warming despite being configured so.

**Comment by casperge** [comment]
The other bug should be fixed now, what is your server TPS (/tps)?

**Comment by aleighco** [comment]
19-20. I'll give the build build a try.

**Comment by aleighco** [comment]
Upgraded and still get exceptions, a couple a second;

[18:13:11 WARN]: [RealisticSeasons] Task #127 for RealisticSeasons v10.2.5 generated an exception
java.lang.NullPointerException: Cannot invoke "me.casperge.realisticseasons.data.chunksaver.ChunkDataHandler.remove(me.casperge.realisticseasons.season.SeasonChunk)" because the return value of "me.casperge.realisticseasons.RealisticSeasons.getAsyncChunkHandler()" is null
        at me.casperge.realisticseasons.runnables.SpringBlockTicker.run(SpringBlockTicker.java:182) ~[RealisticSeasons-10.2.5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-373]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-373]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by aleighco** [comment]
[06:16:36 WARN]: [RealisticSeasons] Task #127 for RealisticSeasons v10.2.6 generated an exception
java.lang.NullPointerException: Cannot invoke "me.casperge.realisticseasons.data.chunksaver.ChunkDataHandler.remove(me.casperge.realisticseasons.season.SeasonChunk)" because the return value of "me.casperge.realisticseasons.RealisticSeasons.getAsyncChunkHandler()" is null
        at me.casperge.realisticseasons.runnables.SpringBlockTicker.run(SpringBlockTicker.java:151) ~[RealisticSeasons-10.2.6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-373]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-373]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-373]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by casperge** [comment]
I think I need a full log, can you upload one here?

**Comment by aleighco** [comment]
I think I just-now figured this out. It was due to a dependency on mythicmobs pulling a class-not-found. Upgrading to 5.2.1 from 4.x solved the problem. 

So, now working for us. Also the temp adjustments seem to be (once again) working properly. Thanks for a great plugin. 

[09:13:34 WARN]: [RealisticSeasons] Task #70 for RealisticSeasons v10.2.6 generated an exception
java.lang.NoClassDefFoundError: io/lumine/mythic/api/skills/conditions/ISkillCondition
	at me.casperge.realisticseasons.RealisticSeasons.enable(RealisticSeasons.java:249) ~[RealisticSeasons-10.2.6.jar:?]
	at me.casperge.realisticseasons.RealisticSeasons$1.run(RealisticSeasons.java:163) ~[RealisticSeasons-10.2.6.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-373]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1114) ~[paper-1.19.3.jar:git-Paper-373]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-373]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.api.skills.conditions.ISkillCondition
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 7 more
